services:
  mongodb:
    image: "mongo:latest"
    container_name: "mongodb"
    ports:
      - "27017:27017"
    volumes:
      - "./docker/data/db:/data/db"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "api"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
